services:
  service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/anisekai.Dockerfile
    image: akionakao/anisekai:alpha
    user: '1000:1000'
    ports:
      - '10000:${SERVER_PORT:-8080}'
    networks:
      - anisekai
    links:
      - "mariadb:mariadb"
      - "transmission:transmission"
    depends_on:
      - mariadb
      - transmission
    volumes:
      - './data/library:/app/library'
  mariadb:
    image: 'mariadb:10.8'
    ports:
      - '10001:${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'anisekai:/var/lib/mysql'
    networks:
      - anisekai
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  transmission:
    build:
      context: .
      dockerfile: .docker/transmission.Dockerfile
    image: akionakao/transmission:4.0.5
    user: '1000:1000'
    ports:
      - '10003:9091'
      - '10004:51423'
    networks:
      - anisekai
    volumes:
      - './data/transmission:/app/data'
      - './data/library/downloads:/app/downloads'
networks:
  anisekai:
    driver: bridge
volumes:
  anisekai:
    driver: local
