services:
  service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: .docker/anisekai.Dockerfile
    image: akionakao/anisekai:alpha
    user: '1000:1000'
    ports:
      - '${FW_SERVICE_PORT:-8080}:${SERVER_PORT:-8080}'
    networks:
      - anisekai
    links:
      - "mariadb:mariadb"
      - "transmission:transmission"
    depends_on:
      - mariadb
      - transmission
    volumes:
      - './data/torrents:/app/data/torrents'
      - './data/web:/app/data/library'
  mariadb:
    image: 'mariadb:11.8.2'
    ports:
      - '${FW_DATABASE_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'anisekai:/var/lib/mysql'
    networks:
      - anisekai
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  transmission:
    build:
      context: .
      dockerfile: .docker/transmission.Dockerfile
    image: akionakao/transmission:4.0.5
    user: '1000:1000'
    ports:
      - '${FW_TRANSMISSION_RPC_PORT:-9091}:9091'
      - '${FW_TRANSMISSION_PEER_PORT:-51423}:51423'
    networks:
      - anisekai
    volumes:
      - './data/transmission:/app/data'
      - './data/torrents:/app/downloads'
networks:
  anisekai:
    driver: bridge
volumes:
  anisekai:
    driver: local
