version: '3.3'
name: 'toshiko'
services:
  service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: toshiko.Dockerfile
    image: akionakao/toshiko
    ports:
      - '8082:${SERVER_PORT:-8080}'
    networks:
      - toshiko
    links:
      - "mariadb:mariadb"
      - "transmission:transmission"
    depends_on:
      - mariadb
      - transmission
    volumes:
      - '/path/to/library:/mnt/nas/storage/library'
  mariadb:
    image: 'mariadb:10.8'
    ports:
      - '3306:${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'toshiko:/var/lib/mysql'
    networks:
      - toshiko
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  transmission:
    build:
      context: .
      dockerfile: transmission.Dockerfile
    image: akionakao/transmission
    user: '1000:1000'
    ports:
      - '9091:9091'
      - '51413:51423'
    networks:
      - dev
    volumes:
      - '/path/to/library:/mnt/nas/storage/library'
      - '/path/to/data:/app/data'
networks:
  toshiko:
    driver: bridge
volumes:
  toshiko:
    driver: local
